/**
 * Vendors Specter's contracts into this repository and generates TypeScript from them.
 *
 *   npm run specter:contracts [-- <specter contracts directory>]
 *
 * The default source is the Specter repository this server is checked out in
 * (integrations/fa/server -> ../../../contracts). Never edit the generated files by hand.
 */
import { copyFile, mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";
import { compile } from "json-schema-to-typescript";

const SERVER_DIRECTORY = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const VENDORED_DIRECTORY = path.join(SERVER_DIRECTORY, "contracts", "specter");
const GENERATED_DIRECTORY = path.join(SERVER_DIRECTORY, "src", "specter", "generated");
// Internal Specter messages (detector jobs, health heartbeats) are not part of fa's contract.
const EVENT_SCHEMA_NAMES = [
  "match_confirmed",
  "rule_triggered",
  "camera_status_changed",
  "enrollment_status_changed",
  "configuration_changed",
];
const BANNER = "// Generated by scripts/syncSpecterContracts.ts from Specter's contracts. Do not edit.\n";

async function vendorContracts(sourceDirectory: string): Promise<void> {
  await mkdir(path.join(VENDORED_DIRECTORY, "jsonschema"), { recursive: true });
  await copyFile(
    path.join(sourceDirectory, "openapi.json"),
    path.join(VENDORED_DIRECTORY, "openapi.json"),
  );
  for (const fileName of await readdir(path.join(sourceDirectory, "jsonschema"))) {
    const schemaName = fileName.replace(/\.schema\.json$/, "");
    if (EVENT_SCHEMA_NAMES.includes(schemaName)) {
      await copyFile(
        path.join(sourceDirectory, "jsonschema", fileName),
        path.join(VENDORED_DIRECTORY, "jsonschema", fileName),
      );
    }
  }
}

async function generateOpenApiTypes(): Promise<void> {
  // Request fields with a default are optional; openapi-typescript would otherwise require them.
  const ast = await openapiTS(pathToFileURL(path.join(VENDORED_DIRECTORY, "openapi.json")), {
    defaultNonNullable: false,
  });
  await writeFile(path.join(GENERATED_DIRECTORY, "openapi.ts"), BANNER + astToString(ast));
}

// Property titles would each become a named alias such as `CameraId = string`, repeated per schema.
function removePropertyTitles(schema: any): void {
  if (schema === null || typeof schema !== "object") return;
  for (const property of Object.values<any>(schema.properties ?? {})) delete property.title;
  for (const value of Object.values(schema)) removePropertyTitles(value);
}

async function generateEventTypesAndSchemas(): Promise<void> {
  const schemaEntries: string[] = [];
  // One document with shared $defs, so types used by several events are declared once.
  const combinedSchema: any = {
    title: "SpecterEvents",
    type: "object",
    additionalProperties: false,
    properties: {},
    $defs: {},
  };
  for (const schemaName of EVENT_SCHEMA_NAMES) {
    const schemaText = await readFile(
      path.join(VENDORED_DIRECTORY, "jsonschema", `${schemaName}.schema.json`),
      "utf8",
    );
    schemaEntries.push(`  ${schemaName}: ${schemaText.trim()},`);
    const { $defs = {}, ...messageSchema } = JSON.parse(schemaText);
    Object.assign(combinedSchema.$defs, $defs, { [messageSchema.title]: messageSchema });
    combinedSchema.properties[schemaName] = { $ref: `#/$defs/${messageSchema.title}` };
  }
  removePropertyTitles(combinedSchema);
  const typeSource = await compile(combinedSchema, "SpecterEvents", {
    bannerComment: "",
    additionalProperties: false,
  });
  await writeFile(path.join(GENERATED_DIRECTORY, "events.ts"), BANNER + typeSource);
  await writeFile(
    path.join(GENERATED_DIRECTORY, "eventSchemas.ts"),
    `${BANNER}export const specterEventSchemas = {\n${schemaEntries.join("\n")}\n} as const;\n`,
  );
}

async function main(): Promise<void> {
  const sourceDirectory = path.resolve(
    process.argv[2] ?? path.join(SERVER_DIRECTORY, "..", "..", "..", "contracts"),
  );
  await mkdir(GENERATED_DIRECTORY, { recursive: true });
  await vendorContracts(sourceDirectory);
  await generateOpenApiTypes();
  await generateEventTypesAndSchemas();
  console.log(`Specter contracts from ${sourceDirectory} written to ${GENERATED_DIRECTORY}`);
}

await main();
